import express from "express";
import * as carController from "../controllers/carController.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
const router = express.Router();
// router.use(authenticate);
router.get("/:id", carController.getCarById);
router.get("", carController.getCars);
router.post("",authMiddleware,carController.createCar);
router.delete("/:id", authMiddleware,carController.deleteCar);
router.put("/:id", authMiddleware,carController.updateCar);
// router.get("/:id", driverController.getDriverByName);
export default router;