import express from "express";
import * as driverController from "../controllers/driverController.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
const router = express.Router();
// router.use(authenticate);
router.get("/:id", authMiddleware,driverController.getDriverById);
router.post("", authMiddleware,driverController.createDriver);
router.delete("/:id", authMiddleware,driverController.deleteDriver);
router.get("", authMiddleware,driverController.getDrivers);
// router.get("/:id", driverController.getDriverByName);
export default router;